# Generated by Django 3.2.9 on 2023-03-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteryqa', '0004_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='select',
            field=models.CharField(choices=[('BatteryBERT-cased', 'BatteryBERT-cased'), ('BatterySciBERT-cased', 'BatterySciBERT-cased'), ('BatteryOnlyBERT-cased', 'BatteryOnlyBERT-cased'), ('BatteryBERT-uncased', 'BatteryBERT-uncased'), ('BatterySciBERT-uncased', 'BatterySciBERT-uncased'), ('BatteryOnlyBERT-uncased', 'BatteryOnlyBERT-uncased')], default='BatteryBERT-cased', max_length=25, verbose_name='Select a model to analyse:'),
        ),
    ]
